apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: k8saas-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: online-boutique
    name: in-cluster
  project: user
  source:
    path: apps/online-boutique
    repoURL: https://github.com/ccl-consulting/k8saas-user-apps
    targetRevision: env/k8saas-zan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
